apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: testapp
  name: testdeployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testApp
  template:
    metadata:
      labels:
        app: testApp
    spec:
      containers:
        - image: cecil7777/test:version1
          name: web
          ports:
            - containerPort: 80
