apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: testapp
  name: testdeployment
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
        - image: cecil7777/test:version2
          name: web
          ports:
            - containerPort: 80
