apiVersion: apps/v1
kind: service
metadata:
  labels:
    app.kubernetes.io/instance: testapp
  name: testapp-service
  namespace: default
spec:
  ports:
    - nodePort: 30008
      port: 80
      targetPort: 80
  selector:
    app: testApp
  type: LoadBalancer
