apiVersion: apps/v1
kind: service
metadata: 
  name: testapp-service  # Not "undefined"—fix if it’s wrong
  namespace: default
spec:
  selector: 
     app: testApp
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008



