apiVersion: apps/v1
kind: service
metadata: 
 labels:
   name: loadblancerservice
spec:
  selector: 
     app: testApp
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008



