apiVersion: v1
kind: Service
metadata:
  name: testapp-service
  namespace: default
spec:
  selector:
    app: testapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

